// FIFA World Cup 2026 — "Annex C: Combinations for the eight best third-placed
// teams" lookup table. 495 rows = C(12, 8), one per possible combination of
// which 8 of the 12 groups produce a qualifying third-placed team.
//
// Source: FIFA World Cup 26 Regulations, Annex C, Article 12.6
// (https://digitalhub.fifa.com/m/636f5c9c6f29771f/original/FWC2026_regulations_EN.pdf).
//
// THIRD_PLACE_WINNER_COLUMNS is the column order: the group whose winner each
// column's R32 opponent is drawn against. Each ANNEX_C_ROWS entry lists the 8
// third-placed group letters in that same column order — e.g. "EJIFHGLK" maps
// the {E,F,G,H,I,J,K,L} combination so 1A plays 3E, 1B plays 3J, 1D plays 3I, …
// The 495 rows are keyed purely by combination (their sorted letters), not by
// FIFA's internal option numbering. Integrity is asserted in the unit test:
// 495 distinct full-coverage combinations, and every assignment respects the
// per-match group constraints in r32-structure.ts.

export const THIRD_PLACE_WINNER_COLUMNS = [
  "A", "B", "D", "E", "G", "I", "K", "L",
] as const;

const ANNEX_C_ROWS: readonly string[] = [
  "EJIFHGLK", "HGIDJFLK", "EJIDHGLK", "EJIDHFLK", "EGIDJFLK", "EGJDHFLK", "EGIDHFLK", "EGJDHFLI", "EGJDHFIK",
  "HGICJFLK", "EJICHGLK", "EJICHFLK", "EGICJFLK", "EGJCHFLK", "EGICHFLK", "EGJCHFLI", "EGJCHFIK", "HGICJDLK",
  "CJIDHFLK", "CGIDJFLK", "CGJDHFLK", "CGIDHFLK", "CGJDHFLI", "CGJDHFIK", "EJICHDLK", "EGICJDLK", "EGJCHDLK",
  "EGICHDLK", "EGJCHDLI", "EGJCHDIK", "CJEDIFLK", "CJEDHFLK", "CEIDHFLK", "CJEDHFLI", "CJEDHFIK", "CGEDJFLK",
  "CGEDIFLK", "CGEDJFLI", "CGEDJFIK", "CGEDHFLK", "CGJDHFLE", "CGJDHFEK", "CGEDHFLI", "CGEDHFIK", "CGJDHFEI",
  "HJBFIGLK", "EJIBHGLK", "EJBFIHLK", "EJBFIGLK", "EJBFHGLK", "EGBFIHLK", "EJBFHGLI", "EJBFHGIK", "HJBDIGLK",
  "HJBDIFLK", "IGBDJFLK", "HGBDJFLK", "HGBDIFLK", "HGBDJFLI", "HGBDJFIK", "EJBDIHLK", "EJBDIGLK", "EJBDHGLK",
  "EGBDIHLK", "EJBDHGLI", "EJBDHGIK", "EJBDIFLK", "EJBDHFLK", "EIBDHFLK", "EJBDHFLI", "EJBDHFIK", "EGBDJFLK",
  "EGBDIFLK", "EGBDJFLI", "EGBDJFIK", "EGBDHFLK", "HGBDJFLE", "HGBDJFEK", "EGBDHFLI", "EGBDHFIK", "HGBDJFEI",
  "HJBCIGLK", "HJBCIFLK", "IGBCJFLK", "HGBCJFLK", "HGBCIFLK", "HGBCJFLI", "HGBCJFIK", "EJBCIHLK", "EJBCIGLK",
  "EJBCHGLK", "EGBCIHLK", "EJBCHGLI", "EJBCHGIK", "EJBCIFLK", "EJBCHFLK", "EIBCHFLK", "EJBCHFLI", "EJBCHFIK",
  "EGBCJFLK", "EGBCIFLK", "EGBCJFLI", "EGBCJFIK", "EGBCHFLK", "HGBCJFLE", "HGBCJFEK", "EGBCHFLI", "EGBCHFIK",
  "HGBCJFEI", "HJBCIDLK", "IGBCJDLK", "HGBCJDLK", "HGBCIDLK", "HGBCJDLI", "HGBCJDIK", "CJBDIFLK", "CJBDHFLK",
  "CIBDHFLK", "CJBDHFLI", "CJBDHFIK", "CGBDJFLK", "CGBDIFLK", "CGBDJFLI", "CGBDJFIK", "CGBDHFLK", "CGBDHFLJ",
  "HGBCJFDK", "CGBDHFLI", "CGBDHFIK", "HGBCJFDI", "EJBCIDLK", "EJBCHDLK", "EIBCHDLK", "EJBCHDLI", "EJBCHDIK",
  "EGBCJDLK", "EGBCIDLK", "EGBCJDLI", "EGBCJDIK", "EGBCHDLK", "HGBCJDLE", "HGBCJDEK", "EGBCHDLI", "EGBCHDIK",
  "HGBCJDEI", "CJBDEFLK", "CEBDIFLK", "CJBDEFLI", "CJBDEFIK", "CEBDHFLK", "CJBDHFLE", "CJBDHFEK", "CEBDHFLI",
  "CEBDHFIK", "CJBDHFEI", "CGBDEFLK", "CGBDJFLE", "CGBDJFEK", "CGBDEFLI", "CGBDEFIK", "CGBDJFEI", "CGBDHFLE",
  "CGBDHFEK", "HGBCJFDE", "CGBDHFEI", "HJIFAGLK", "EJIAHGLK", "EJIFAHLK", "EJIFAGLK", "EGJFAHLK", "EGIFAHLK",
  "EGJFAHLI", "EGJFAHIK", "HJIDAGLK", "HJIDAFLK", "IGJDAFLK", "HGJDAFLK", "HGIDAFLK", "HGJDAFLI", "HGJDAFIK",
  "EJIDAHLK", "EJIDAGLK", "EGJDAHLK", "EGIDAHLK", "EGJDAHLI", "EGJDAHIK", "EJIDAFLK", "HJEDAFLK", "HEIDAFLK",
  "HJEDAFLI", "HJEDAFIK", "EGJDAFLK", "EGIDAFLK", "EGJDAFLI", "EGJDAFIK", "HGEDAFLK", "HGJDAFLE", "HGJDAFEK",
  "HGEDAFLI", "HGEDAFIK", "HGJDAFEI", "HJICAGLK", "HJICAFLK", "IGJCAFLK", "HGJCAFLK", "HGICAFLK", "HGJCAFLI",
  "HGJCAFIK", "EJICAHLK", "EJICAGLK", "EGJCAHLK", "EGICAHLK", "EGJCAHLI", "EGJCAHIK", "EJICAFLK", "HJECAFLK",
  "HEICAFLK", "HJECAFLI", "HJECAFIK", "EGJCAFLK", "EGICAFLK", "EGJCAFLI", "EGJCAFIK", "HGECAFLK", "HGJCAFLE",
  "HGJCAFEK", "HGECAFLI", "HGECAFIK", "HGJCAFEI", "HJICADLK", "IGJCADLK", "HGJCADLK", "HGICADLK", "HGJCADLI",
  "HGJCADIK", "CJIDAFLK", "HJFCADLK", "HFICADLK", "HJFCADLI", "HJFCADIK", "CGJDAFLK", "CGIDAFLK", "CGJDAFLI",
  "CGJDAFIK", "HGFCADLK", "CGJDAFLH", "HGJCAFDK", "HGFCADLI", "HGFCADIK", "HGJCAFDI", "EJICADLK", "HJECADLK",
  "HEICADLK", "HJECADLI", "HJECADIK", "EGJCADLK", "EGICADLK", "EGJCADLI", "EGJCADIK", "HGECADLK", "HGJCADLE",
  "HGJCADEK", "HGECADLI", "HGECADIK", "HGJCADEI", "CJEDAFLK", "CEIDAFLK", "CJEDAFLI", "CJEDAFIK", "HEFCADLK",
  "HJFCADLE", "HJECAFDK", "HEFCADLI", "HEFCADIK", "HJECAFDI", "CGEDAFLK", "CGJDAFLE", "CGJDAFEK", "CGEDAFLI",
  "CGEDAFIK", "CGJDAFEI", "HGFCADLE", "HGECAFDK", "HGJCAFDE", "HGECAFDI", "HJBAIGLK", "HJBAIFLK", "IJBFAGLK",
  "HJBFAGLK", "HGBAIFLK", "HJBFAGLI", "HJBFAGIK", "EJBAIHLK", "EJBAIGLK", "EJBAHGLK", "EGBAIHLK", "EJBAHGLI",
  "EJBAHGIK", "EJBAIFLK", "EJBFAHLK", "EIBFAHLK", "EJBFAHLI", "EJBFAHIK", "EJBFAGLK", "EGBAIFLK", "EJBFAGLI",
  "EJBFAGIK", "EGBFAHLK", "HJBFAGLE", "HJBFAGEK", "EGBFAHLI", "EGBFAHIK", "HJBFAGEI", "IJBDAHLK", "IJBDAGLK",
  "HJBDAGLK", "IGBDAHLK", "HJBDAGLI", "HJBDAGIK", "IJBDAFLK", "HJBDAFLK", "HIBDAFLK", "HJBDAFLI", "HJBDAFIK",
  "FJBDAGLK", "IGBDAFLK", "FJBDAGLI", "FJBDAGIK", "HGBDAFLK", "HGBDAFLJ", "HGBDAFJK", "HGBDAFLI", "HGBDAFIK",
  "HGBDAFIJ", "EJBAIDLK", "EJBDAHLK", "EIBDAHLK", "EJBDAHLI", "EJBDAHIK", "EJBDAGLK", "EGBAIDLK", "EJBDAGLI",
  "EJBDAGIK", "EGBDAHLK", "HJBDAGLE", "HJBDAGEK", "EGBDAHLI", "EGBDAHIK", "HJBDAGEI", "EJBDAFLK", "EIBDAFLK",
  "EJBDAFLI", "EJBDAFIK", "HEBDAFLK", "HJBDAFLE", "HJBDAFEK", "HEBDAFLI", "HEBDAFIK", "HJBDAFEI", "EGBDAFLK",
  "EGBDAFLJ", "EGBDAFJK", "EGBDAFLI", "EGBDAFIK", "EGBDAFIJ", "HGBDAFLE", "HGBDAFEK", "HGBDAFEJ", "HGBDAFEI",
  "IJBCAHLK", "IJBCAGLK", "HJBCAGLK", "IGBCAHLK", "HJBCAGLI", "HJBCAGIK", "IJBCAFLK", "HJBCAFLK", "HIBCAFLK",
  "HJBCAFLI", "HJBCAFIK", "CJBFAGLK", "IGBCAFLK", "CJBFAGLI", "CJBFAGIK", "HGBCAFLK", "HGBCAFLJ", "HGBCAFJK",
  "HGBCAFLI", "HGBCAFIK", "HGBCAFIJ", "EJBAICLK", "EJBCAHLK", "EIBCAHLK", "EJBCAHLI", "EJBCAHIK", "EJBCAGLK",
  "EGBAICLK", "EJBCAGLI", "EJBCAGIK", "EGBCAHLK", "HJBCAGLE", "HJBCAGEK", "EGBCAHLI", "EGBCAHIK", "HJBCAGEI",
  "EJBCAFLK", "EIBCAFLK", "EJBCAFLI", "EJBCAFIK", "HEBCAFLK", "HJBCAFLE", "HJBCAFEK", "HEBCAFLI", "HEBCAFIK",
  "HJBCAFEI", "EGBCAFLK", "EGBCAFLJ", "EGBCAFJK", "EGBCAFLI", "EGBCAFIK", "EGBCAFIJ", "HGBCAFLE", "HGBCAFEK",
  "HGBCAFEJ", "HGBCAFEI", "IJBCADLK", "HJBCADLK", "HIBCADLK", "HJBCADLI", "HJBCADIK", "CJBDAGLK", "IGBCADLK",
  "CJBDAGLI", "CJBDAGIK", "HGBCADLK", "HGBCADLJ", "HGBCADJK", "HGBCADLI", "HGBCADIK", "HGBCADIJ", "CJBDAFLK",
  "CIBDAFLK", "CJBDAFLI", "CJBDAFIK", "HFBCADLK", "CJBDAFLH", "HJBCAFDK", "HFBCADLI", "HFBCADIK", "HJBCAFDI",
  "CGBDAFLK", "CGBDAFLJ", "CGBDAFJK", "CGBDAFLI", "CGBDAFIK", "CGBDAFIJ", "CGBDAFLH", "HGBCAFDK", "HGBCAFDJ",
  "HGBCAFDI", "EJBCADLK", "EIBCADLK", "EJBCADLI", "EJBCADIK", "HEBCADLK", "HJBCADLE", "HJBCADEK", "HEBCADLI",
  "HEBCADIK", "HJBCADEI", "EGBCADLK", "EGBCADLJ", "EGBCADJK", "EGBCADLI", "EGBCADIK", "EGBCADIJ", "HGBCADLE",
  "HGBCADEK", "HGBCADEJ", "HGBCADEI", "CEBDAFLK", "CJBDAFLE", "CJBDAFEK", "CEBDAFLI", "CEBDAFIK", "CJBDAFEI",
  "HFBCADLE", "HEBCAFDK", "HJBCAFDE", "HEBCAFDI", "CGBDAFLE", "CGBDAFEK", "CGBDAFEJ", "CGBDAFEI", "HGBCAFDE",
];

// combination key (sorted group letters) -> row in THIRD_PLACE_WINNER_COLUMNS order
const ALLOCATION_BY_COMBINATION = new Map<string, string>(
  ANNEX_C_ROWS.map((row) => [[...row].sort().join(""), row] as const),
);

// Given the eight groups whose third-placed team qualifies, return the map
// winnerGroup -> thirdPlaceGroup that fixes each "winner v. best third" R32
// match. Returns an empty map until exactly eight groups are supplied (the
// allocation is undefined before then), or if the combination is unknown.
export function allocateThirdPlaces(
  qualifyingGroups: readonly string[],
): Map<string, string> {
  const allocation = new Map<string, string>();
  if (qualifyingGroups.length !== THIRD_PLACE_WINNER_COLUMNS.length) return allocation;
  const row = ALLOCATION_BY_COMBINATION.get([...qualifyingGroups].sort().join(""));
  if (!row) return allocation;
  THIRD_PLACE_WINNER_COLUMNS.forEach((winnerGroup, i) => {
    allocation.set(winnerGroup, row[i]!);
  });
  return allocation;
}
